name: Test Java

on:
  pull_request:
    branches:
      - '**'
  workflow_call:
  push:
    branches:
      - main
      - renovate/**

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        version: [ 17, 19 ]
    name: 'Build Java ${{ matrix.version }} - ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.version }}
          cache: 'maven'
      - name: Install dependencies
        run: mvn install -DskipTests=true -DskipITs=true --batch-mode -D"style.color=always" --show-version
      - name: Test
        run: mvn verify -D"style.color=always"
        env:
          CUCUMBER_PUBLISH_TOKEN: ${{ secrets.CUCUMBER_PUBLISH_TOKEN }}
